// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQmcWZiR3Kgd288IH2iXQYHCIfk4WlLI',
    appId: '1:718967986293:web:4f38f8bd1d47f192d6803c',
    messagingSenderId: '718967986293',
    projectId: 'parkingapps-a06a2',
    authDomain: 'parkingapps-a06a2.firebaseapp.com',
    databaseURL: 'https://parkingapps-a06a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkingapps-a06a2.appspot.com',
    measurementId: 'G-1H6FJC5F0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcrx2OZxSfKujLHZl6CZBeW3afWX8dz2I',
    appId: '1:718967986293:android:d30f69df9424eefbd6803c',
    messagingSenderId: '718967986293',
    projectId: 'parkingapps-a06a2',
    databaseURL: 'https://parkingapps-a06a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkingapps-a06a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSK2DBexteBWO22J17YltaAWCtW1ZPvM',
    appId: '1:718967986293:ios:2d20acc3e382e439d6803c',
    messagingSenderId: '718967986293',
    projectId: 'parkingapps-a06a2',
    databaseURL: 'https://parkingapps-a06a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkingapps-a06a2.appspot.com',
    iosBundleId: 'com.example.parkingapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSK2DBexteBWO22J17YltaAWCtW1ZPvM',
    appId: '1:718967986293:ios:1458fe0590bfa6c6d6803c',
    messagingSenderId: '718967986293',
    projectId: 'parkingapps-a06a2',
    databaseURL: 'https://parkingapps-a06a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkingapps-a06a2.appspot.com',
    iosBundleId: 'com.example.parkingapps.RunnerTests',
  );
}
